version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  postgres:
    container_name: "${DB_HOST}"
    image: postgres:14.7-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
